In [5]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:

b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
b.ndim

2

In [11]:
print(a.dtype)
print(b.shape)

int32
(3, 5)


In [15]:
print(a.size)
print(b.itemsize)

15
4


In [7]:
c=np.array([(1.5,2,3), (4,5,6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
d=np.array([(1,2),(3,4)], dtype=complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
np.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
np.empty(2)

array([1.34549719e-311, 4.94065646e-324])

In [23]:
np.ones(2)

array([1., 1.])

In [24]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [28]:
np.linspace(0,10,num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [31]:
rg= np.random.default_rng(1)
a= np.floor(10 * rg.random((3,4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [32]:
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [33]:
a.ndim

2

In [35]:
x=np.array(((5,2,3),(7,9,1)))
np.sum(x<6,axis=1)

array([3, 1])

In [ ]:
np.zeros((3,4))

In [41]:
zeros=np.zeros((2,4), dtype=int)
ones=np.ones(4, dtype=int)
print(zeros)
print(ones)

b=np.vstack((ones, zeros))

[[0 0 0 0]
 [0 0 0 0]]
[1 1 1 1]


In [42]:
b

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
zeros=np.zeros((2,4), dtype=int)
range=np.arange(5,9)

np.vstack((zeros,range))

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [5, 6, 7, 8]])